GET http://localhost:3000/contacts


### get single contact
GET http://localhost:3000/contacts/6448994090b41b8ad8eb37db



### Create contact 

POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
"firstName":"nicole", "lastName":"Weaver", "email":"aWeaver@test.com", "favoriteColor":"Brown", "birthday":"06/19/2000"
}


### PUT contact 
PUT http://localhost:3000/contacts/6448994090b41b8ad8eb37db HTTP/1.1
content-type: application/json

{
"firstName":"Camila","lastName":"Gallegos","email":"camigm2@test.com","favoriteColor":"Purple","birthday":"12/12/20"
} 

### DELETE contact 
DELETE http://localhost:3000/contacts/64518807f87aa7450494b1b1 HTTP/1.1


// PRODUCTION Deploy 

### Get all contacts 
GET https://l2-connect-api-to-a-database.onrender.com/contacts

### Get contact by id 

GET https://l2-connect-api-to-a-database.onrender.com/contacts/6448994090b41b8ad8eb37db

### Create contact 

POST https://l2-connect-api-to-a-database.onrender.com/contacts HTTP/1.1
content-type: application/json

{
"firstName":"Ashley", "lastName":"Weaver", "email":"aWeaver@test.com", "favoriteColor":"Brown", "birthday":"06/19/2000"
}

### PUT contact 

PUT https://l2-connect-api-to-a-database.onrender.com/contacts/64518807f87aa7450494b1b1 HTTP/1.1
content-type: application/json

{
"firstName":"Sarah", "lastName":"Birch", "email":"sarahB@gmail.com", "favoriteColor":"Yellow", "birthday":"06/12/20"
}

### DELETE contact 
DELETE https://l2-connect-api-to-a-database.onrender.com/contacts/6453e962c613575bc85cfac5 HTTP/1.1
